### ISSUE TITLE
python setup.py install fails: no file or directory README.rst

### ISSUE THREAD

**Issue by anees042** [rhdunn/cmudict-tools#1]
Please note, python setup.py install fails with the following error;

`File "./setup.py", line 34, in <module>
    long_description=read_file('README.rst'),
  File "./setup.py", line 28, in read_file
    with codecs.open(filename, 'r', encoding) as f:
  File "/usr/lib/python2.7/codecs.py", line 896, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 2] No such file or directory: 'README.rst'`

I simply created a dummy file and the installation went successfully.

Thanks..

**Comment by rhdunn** [comment]
I have added build instructions. The `README.rst` file is generated by running:

    make README.rst

or, if you are installing, you can just run:

    make install

The `README.md` file is in Markdown format, not ReStructured Text (RST) format. I am not going to rename/convert the file as it is easy to convert the file using `pandoc` as the `Makefile` does.
